[package]
name = "driad"
version = "0.1.0"
edition = "2024"

[dependencies]
sdl3 = { version = "0.17.3", features = [] }

thiserror = { version = "2.0.18", features = [] }

mlua = { version = "0.11.6", features = ["lua54", "macros"] }
